Repository k1g99/SwithS, pull requests merged in 2023-11, with the labels that each got.

#25 페이지 생성(검색, 글쓰기)
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/Pages/MystudyPage.js
  frontend/src/Pages/SearchPage.js
  frontend/src/Pages/WritePage1.js
  frontend/src/components/Dropdown.js
  frontend/src/components/Home/Header1.js
  frontend/src/components/SelectBox.js
  frontend/src/components/StudyCard.js
  frontend/src/images/dropdown.svg
Labels: 🚩Team-FE

#36 Feature/35 uploadpage
  frontend/src/App.js
  frontend/src/Pages/LoginPage.js
  frontend/src/Pages/MyPage.js
  frontend/src/Pages/RegisterPage.js
  frontend/src/Pages/SearchPage.js
  frontend/src/Pages/UploadPage.js
  frontend/src/Pages/WritePage.js
  frontend/src/Pages/WritePage2.js
  frontend/src/components/Button1.js
  frontend/src/components/Button2.js
  frontend/src/components/Button3.js
  frontend/src/components/Calender.js
  frontend/src/components/Dropdown.js
  frontend/src/components/Home/SectionCat.js
  frontend/src/components/Home/SectionHot.js
  frontend/src/components/InputBox1.js
  frontend/src/components/InputBox2.js
  frontend/src/components/SelectBox.js
  frontend/src/components/Sidebar1.js
  frontend/src/components/StudyCard.js
  frontend/src/components/TextInput.js
  frontend/src/images/upload.svg
  frontend/src/index.css
Labels: 🚩Team-FE

#37 FIX: 스터디 조회 정렬 알고리즘 추가 마감기한+생성날짜 순
  backend/src/main/java/com/teamk/swiths_api/club/repository/ClubEntity.java
  backend/src/main/java/com/teamk/swiths_api/club/repository/ClubRepository.java
  backend/src/main/java/com/teamk/swiths_api/club/service/ClubServiceImpl.java
  backend/src/main/resources/db/data.sql
Labels: 🚩Team-BE

#43 Feature/41 datailpage
  frontend/src/App.js
  frontend/src/Pages/DetailPage.js
  frontend/src/Pages/UploadPage.js
  frontend/src/Pages/WritePage.js
  frontend/src/components/DetailText.js
  frontend/src/components/TextInput.js
Labels: 🚩Team-FE

#40 API 서버 생성합니다.
  .github/workflows/dev-server.yml
  .gitignore
  backend/Dockerfile
  backend/src/main/resources/application.yml
  docker-compose-dev.yml
  frontend/package.json
  frontend/src/Pages/WritePage.js
  frontend/src/api.js
Labels: 🚩Team-BE

#46 상세 페이지 데이터 불러오기
  frontend/src/App.js
  frontend/src/Pages/DetailPage.js
  frontend/src/Pages/SearchPage.js
  frontend/src/components/DetailText.js
Labels: 🚩Team-FE

#48 Feature/34 make register api
  .gitignore
  backend/build.gradle
  backend/src/main/java/com/teamk/swiths_api/user/controller/UserController.java
  backend/src/main/java/com/teamk/swiths_api/user/controller/dto/Email.java
  backend/src/main/java/com/teamk/swiths_api/user/service/MailService.java
  backend/src/main/java/com/teamk/swiths_api/user/service/RedisUtil.java
  backend/src/main/java/com/teamk/swiths_api/user/service/UserService.java
  backend/src/main/java/com/teamk/swiths_api/user/service/UserServiceImpl.java
  backend/src/main/resources/application.yml
  docker-compose.yml
Labels: 🚩Team-BE

#52 fix: fix spring config
  backend/src/main/resources/application.yml
Labels: 🪲 bug

#57 deploy 브랜치 PR일 때 Action 해제
  .github/workflows/dev-server.yml
Labels: 🪲 bug

#54 Major Get API 생성
  .gitignore
  backend/src/main/java/com/teamk/swiths_api/club/repository/ClubEntity.java
  backend/src/main/java/com/teamk/swiths_api/club/service/ClubServiceImpl.java
  backend/src/main/java/com/teamk/swiths_api/major/controller/MajorController.java
  backend/src/main/java/com/teamk/swiths_api/major/repository/MajorEntity.java
  backend/src/main/java/com/teamk/swiths_api/major/repository/MajorMapping.java
  backend/src/main/java/com/teamk/swiths_api/major/repository/MajorRepository.java
  backend/src/main/java/com/teamk/swiths_api/major/repository/dto/FindAllMajorResponse.java
  backend/src/main/java/com/teamk/swiths_api/major/service/MajorService.java
  backend/src/main/java/com/teamk/swiths_api/major/service/MajorServiceImpl.java
  backend/src/main/java/com/teamk/swiths_api/user/repository/entity/UserEntity.java
  backend/src/main/java/com/teamk/swiths_api/user/service/UserServiceImpl.java
  frontend/src/Pages/WritePage.js
Labels: 🚩Team-BE
