Repository k1g99/SwithS, pull requests merged in 2023-12, with the labels that each got.

#58 메인, 회원가입 페이지 수정
  backend/src/main/java/com/teamk/swiths_api/club/repository/ClubEntity.java
  backend/src/main/java/com/teamk/swiths_api/club/service/ClubServiceImpl.java
  backend/src/main/java/com/teamk/swiths_api/config/SecurityConfig.java
  backend/src/main/java/com/teamk/swiths_api/major/repository/MajorEntity.java
  backend/src/main/java/com/teamk/swiths_api/user/controller/UserController.java
  frontend/src/App.js
  frontend/src/Pages/CategoryPage.js
  frontend/src/Pages/DetailPage.js
  frontend/src/Pages/RegisterPage.js
  frontend/src/Pages/SearchPage.js
  frontend/src/Pages/WritePage.js
  frontend/src/components/Button2.js
  frontend/src/components/Button3.js
  frontend/src/components/Button4.js
  frontend/src/components/Home/Search.js
  frontend/src/components/Home/SectionCat.js
  frontend/src/components/InputBox2.js
  frontend/src/components/SelectBox.js
  frontend/src/components/StudyCard.js
Labels: 🚩Team-FE

#77 hotfix 잘못된 symbol 수정
  backend/src/main/java/com/teamk/swiths_api/post/repository/dto/VoteItemDetailDto.java
Labels: 🪲 bug, 🚩Team-BE

#69 공지, 자료실
  frontend/src/App.js
  frontend/src/Pages/LoginPage.js
  frontend/src/Pages/MyPage.js
  frontend/src/Pages/MystudyPage.js
  frontend/src/Pages/NoticedetailPage.js
  frontend/src/Pages/NoticeuploadPage.js
  frontend/src/Pages/ResourcePage.js
  frontend/src/Pages/ResourcedetailPage.js
  frontend/src/Pages/ResourceuploadPage.js
  frontend/src/Pages/ScheduleuploadPage.js
  frontend/src/Pages/SearchPage.js
  frontend/src/Pages/StudydetailPage.js
  frontend/src/Pages/StudyroomPage.js
  frontend/src/components/Button3.js
  frontend/src/components/Button4.js
  frontend/src/components/Comment.js
  frontend/src/components/Dropdown.js
  frontend/src/components/InputBox1.js
  frontend/src/components/NoticeCard.js
  frontend/src/components/ResourceCard.js
  frontend/src/components/SelectBox.js
  frontend/src/components/Sidebar2.js
Labels: 🚩Team-FE

#85 fix: search, category page 오류 수정
  frontend/src/Pages/CategoryPage.js
  frontend/src/Pages/SearchPage.js
  frontend/src/components/Button4.js
Labels: 🪲 bug, 🚩Team-FE

#86 로그인 API 연결
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/Pages/LoginPage.js
  frontend/src/Pages/WritePage.js
  frontend/src/components/Button1.js
  frontend/src/components/Button2.js
  frontend/src/components/Button4.js
  frontend/src/components/Dropdown.js
  frontend/src/components/Home/Header1.js
  frontend/src/components/InputBox1.js
  frontend/src/components/global/cookie.js
  frontend/src/components/hooks/UserLogin.js
Labels: 🚩Team-FE

#92 최신글 클릭 시 페이지 이동
  frontend/src/Pages/HomePage.js
  frontend/src/components/Home/SectionHot.js
Labels: 🚩Team-FE

#93 타임테이블
  frontend/src/Pages/ResourceuploadPage.js
  frontend/src/Pages/ScheduleuploadPage.js
  frontend/src/components/Dropdown.js
Labels: 🚩Team-FE

#110 스터디 생성 이후에 바로 멤버로 등록합니다
  backend/src/main/java/com/teamk/swiths_api/club/controller/ClubController.java
  backend/src/main/java/com/teamk/swiths_api/club/repository/ClubEntity.java
  backend/src/main/java/com/teamk/swiths_api/club/repository/dto/CreateClub.java
  backend/src/main/java/com/teamk/swiths_api/user/controller/UserClubController.java
  frontend/src/Pages/NoticedetailPage.js
  frontend/src/Pages/StudydetailPage.js
  frontend/src/Pages/UserStudyPage.js
  frontend/src/Pages/WritePage.js
  frontend/src/components/Home/Header1.js
  frontend/src/components/NoticeCard.js
Labels: 🚩Team-FE, 🚩Team-BE

#115 디자인 수정
  frontend/src/Pages/HomePage.js
  frontend/src/Pages/LoginPage.js
  frontend/src/Pages/NoticeuploadPage.js
  frontend/src/Pages/ResourceuploadPage.js
  frontend/src/Pages/ScheduleuploadPage.js
  frontend/src/Pages/SearchPage.js
  frontend/src/components/Button4.js
  frontend/src/components/Dropdown.js
  frontend/src/components/Home/Header1.js
  frontend/src/components/Home/SectionHot.js
  frontend/src/components/MyStudyCard.js
  frontend/src/components/Sidebar1.js
  frontend/src/components/StudyCard.js
Labels: 🚩Team-FE
